/**
 * /demo/annex-iv — pre-built Annex IV demos, no install required.
 *
 * Three cards (loan-screener / cv-screener / customer-support) backed
 * by `GET /api/v1/tools/demo/{slug}/annex-iv?format=pdf`. Each card
 * shows the SDK snippet for that use case + opens the rendered PDF
 * inline in a new tab.
 *
 * Server component. The catalogue comes from
 * `GET /api/v1/tools/demo/scenarios` (24h revalidate). The PDFs are
 * served from the backend with Cache-Control: public, max-age=3600
 * so Cloudflare can cache across visitors.
 */

import type { Metadata } from "next";
import Link from "next/link";

import { BackendUnavailable } from "@/components/BackendUnavailable";
import { Disclaimer } from "@/components/Disclaimer";
import { ToolsBreadcrumb } from "@/components/tools/breadcrumb";
import { ToolsCrossLinks } from "@/components/tools/cross-links";
import { Button } from "@/components/ui/button";
import { BACKEND_URL, BackendUnavailableError, CLIENT_API_URL } from "@/lib/api";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "Live Annex IV Demo",
  description:
    "See three real EU AI Act Annex IV PDFs generated by AnnexKit. " +
    "Loan screener (HIGH), CV screener (HIGH), customer-support chatbot " +
    "(LIMITED). No install, no signup — just three clicks.",
  alternates: { canonical: "/demo/annex-iv" },
};

const SITE_ORIGIN =
  process.env.NEXT_PUBLIC_SITE_URL ?? "https://annexkit.dev";
const PAGE_URL = `${SITE_ORIGIN}/demo/annex-iv`;

/**
 * Structured data — BreadcrumbList placing the demo under "Tools"
 * (semantically it's a tool-adjacent page; under the same breadcrumb
 * hierarchy keeps Google's site graph clean). The page itself is also
 * declared as a `WebPage` with a `SoftwareApplication` mainEntity, so
 * Google can pull both a breadcrumb and an entity card.
 */
const BREADCRUMB_LD = {
  "@context": "https://schema.org",
  "@type": "BreadcrumbList",
  itemListElement: [
    { "@type": "ListItem", position: 1, name: "AnnexKit", item: SITE_ORIGIN },
    {
      "@type": "ListItem",
      position: 2,
      name: "Tools",
      item: `${SITE_ORIGIN}/tools`,
    },
    {
      "@type": "ListItem",
      position: 3,
      name: "Live demo",
      item: PAGE_URL,
    },
  ],
};

const DEMO_LD = {
  "@context": "https://schema.org",
  "@type": "WebPage",
  name: "Live Annex IV Demo",
  url: PAGE_URL,
  inLanguage: "en",
  isPartOf: {
    "@type": "WebSite",
    name: "AnnexKit",
    url: SITE_ORIGIN,
  },
  mainEntity: {
    "@type": "SoftwareApplication",
    name: "AnnexKit Annex IV demo",
    applicationCategory: "BusinessApplication",
    applicationSubCategory: "EU AI Act compliance",
    operatingSystem: "Any (browser-based)",
    inLanguage: "en",
    isAccessibleForFree: true,
    offers: {
      "@type": "Offer",
      price: "0",
      priceCurrency: "EUR",
      availability: "https://schema.org/InStock",
    },
    publisher: {
      "@type": "Organization",
      name: "AnnexKit",
      url: SITE_ORIGIN,
    },
  },
  description:
    "Three real EU AI Act Annex IV PDFs generated live by AnnexKit. " +
    "Loan screener (HIGH), CV screener (HIGH), customer-support chatbot " +
    "(LIMITED). No install, no signup.",
};

interface DemoScenario {
  slug: string;
  name: string;
  tier: string;
  annex_iii: string;
  model: string;
  tagline: string;
}

interface DemoScenariosResponse {
  scenarios: DemoScenario[];
}

// Force dynamic — see /tools/annex-iv-generator/page.tsx for the
// full rationale (build container can't reach backend → cached
// fallback). Each request triggers a live backend fetch.
export const dynamic = "force-dynamic";

async function fetchScenarios(): Promise<DemoScenario[] | null> {
  try {
    const res = await fetch(`${BACKEND_URL}/api/v1/tools/demo/scenarios`, {
      cache: "no-store",
    });
    if (!res.ok) {
      throw new BackendUnavailableError(`Demo scenarios fetch failed: HTTP ${res.status}`);
    }
    const data = (await res.json()) as DemoScenariosResponse;
    return data.scenarios;
  } catch (err) {
    if (err instanceof BackendUnavailableError) throw err;
    throw new BackendUnavailableError("Network failure reaching the demo endpoint.");
  }
}

const TIER_COLORS: Record<string, string> = {
  unacceptable: "bg-red-500 text-white",
  high: "bg-orange-500 text-white",
  limited: "bg-amber-400 text-black",
  minimal: "bg-emerald-500 text-white",
};

const SNIPPETS: Record<string, string> = {
  "loan-screener": `from annexkit import track
from openai import OpenAI

@track(
    system_id="loan-screener",
    risk_tier="auto",
    purpose="pre-screen small-business loan applications",
)
def screen(applicant: dict) -> str:
    return OpenAI().chat.completions.create(
        model="gpt-4o-mini",
        messages=[...]
    ).choices[0].message.content`,
  "cv-screener": `from annexkit import track
from anthropic import Anthropic

@track(
    system_id="cv-screener",
    risk_tier="auto",
    purpose="produce structured shortlist notes for recruiters",
)
def screen(candidate: dict) -> str:
    resp = Anthropic().messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=512,
        messages=[...]
    )
    return resp.content[0].text`,
  "customer-support": `import annexkit
from mistralai.client import Mistral

@annexkit.track(
    system_id="customer-support",
    risk_tier="auto",
    purpose="answer shipping and returns questions",
)
def answer(question: str) -> str:
    resp = Mistral().chat.complete(
        model="mistral-small-latest",
        messages=[...]
    )
    return resp.choices[0].message.content`,
};

export default async function DemoAnnexIVPage() {
  let scenarios: DemoScenario[] | null;
  try {
    scenarios = await fetchScenarios();
  } catch {
    return <BackendUnavailable pageLabel="The live Annex IV demo" />;
  }
  if (!scenarios || scenarios.length === 0) {
    return <BackendUnavailable pageLabel="The live Annex IV demo" />;
  }

  return (
    <main className="mx-auto w-full max-w-6xl px-6 py-12">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(BREADCRUMB_LD) }}
      />
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(DEMO_LD) }}
      />
      <ToolsBreadcrumb
        items={[
          { label: "Tools", href: "/tools" },
          { label: "Live demo" },
        ]}
      />
      <header className="mt-6 mb-12 space-y-4">
        <span className="eyebrow">Live demo</span>
        <h1 className="text-4xl font-bold tracking-tight text-foreground">
          See AnnexKit produce a real Annex IV
        </h1>
        <p className="text-lg text-muted-foreground">
          Three pre-built scenarios. Each card opens a fully-rendered EU AI Act
          Annex IV PDF, populated from realistic-looking synthetic telemetry —
          the same shape your own systems would produce with the SDK.
        </p>
        <p className="text-sm text-muted-foreground">
          No install. No signup. Click a card.
        </p>
      </header>

      <section className="grid gap-6 md:grid-cols-3">
        {scenarios.map((s) => (
          <article
            key={s.slug}
            className="flex flex-col rounded-lg border border-border bg-card p-6"
          >
            <div className="mb-3 flex items-center justify-between gap-2">
              <span
                className={cn(
                  "rounded px-2 py-0.5 text-xs font-semibold uppercase",
                  TIER_COLORS[s.tier] ?? "bg-muted",
                )}
              >
                {s.tier}
              </span>
              <span className="text-xs text-muted-foreground">{s.model}</span>
            </div>
            <h2 className="mb-2 text-lg font-semibold text-foreground">{s.name}</h2>
            <p className="mb-2 text-xs text-muted-foreground">{s.annex_iii}</p>
            <p className="mb-4 flex-1 text-sm text-muted-foreground">{s.tagline}</p>
            <details className="mb-4 rounded-md border border-border bg-background p-3 text-xs">
              <summary className="cursor-pointer select-none text-muted-foreground">
                Code (the @track decorator for this scenario)
              </summary>
              <pre className="mt-3 overflow-x-auto text-[11px] leading-relaxed">
                <code>{SNIPPETS[s.slug] ?? ""}</code>
              </pre>
            </details>
            <div className="flex flex-col gap-2">
              <Button asChild className="w-full">
                <a
                  href={`${CLIENT_API_URL}/api/v1/tools/demo/${s.slug}/annex-iv?format=pdf`}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Open Annex IV PDF →
                </a>
              </Button>
              <Button asChild variant="secondary" className="w-full text-xs">
                <a
                  href={`${CLIENT_API_URL}/api/v1/tools/demo/${s.slug}/annex-iv?format=md`}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  …or Markdown
                </a>
              </Button>
            </div>
          </article>
        ))}
      </section>

      <section className="mt-16 grid gap-8 md:grid-cols-2">
        <div className="space-y-3">
          <h2 className="text-2xl font-semibold text-foreground">
            How this works
          </h2>
          <p className="text-sm text-muted-foreground">
            Each scenario is a hardcoded <code className="inline-code">AnnexIVContext</code>{" "}
            in <code className="inline-code">app/services/demo_scenarios.py</code>:
            system declaration, span aggregations (counts, latency p50/p95/p99,
            error breakdown, models used), provider info. The same renderer that
            produces your real PDFs (Jinja → WeasyPrint) is what makes the demo.
          </p>
          <p className="text-sm text-muted-foreground">
            <strong>Nothing is persisted.</strong> No tenant is created. No row
            lands in our database. The PDF is generated in memory, cached by
            Cloudflare for an hour, and gone.
          </p>
        </div>
        <div className="space-y-3">
          <h2 className="text-2xl font-semibold text-foreground">
            Want to do this on your own systems?
          </h2>
          <p className="text-sm text-muted-foreground">
            Drop the <code className="inline-code">@track</code> decorator on the
            functions wrapping your LLM calls. Spans flow to the collector. After
            a week of traffic, the Annex IV PDF looks exactly like one of these
            — with your actual numbers.
          </p>
          <div className="flex flex-wrap gap-2">
            <Button asChild>
              <Link href="/tools/annex-iv-generator">Try the form generator</Link>
            </Button>
            <Button asChild variant="secondary">
              <a
                href="https://github.com/annexkit/annexkit"
                target="_blank"
                rel="noopener noreferrer"
              >
                pip install annexkit
              </a>
            </Button>
          </div>
        </div>
      </section>

      <ToolsCrossLinks exclude="/demo/annex-iv" />

      <div className="mt-12 border-t border-border pt-8">
        <Disclaimer />
      </div>
    </main>
  );
}
