"""Seed a demo tenant + 3 AI systems for the public trust page.

Production-safe — bypasses the dev-only guard in seed_tenant.py because
this script never prints sensitive data unless explicitly asked. The
tenant is named "Acme SaaS" with slug "acme-saas" so the resulting
trust page lives at https://annexkit.dev/trust/acme-saas.

What it creates
---------------

  * One tenant ("Acme SaaS S.r.l.", slug "acme-saas").
  * One API key for that tenant — printed once on success.
  * Three AI system declarations covering the three risk-tier badges
    a homepage visitor should see:
      - customer-support-bot  — LIMITED (Article 50 transparency)
      - cv-screener           — HIGH    (Annex III §4 employment)
      - loan-prescreen        — HIGH    (Annex III §5 essential services)

The demo systems use sanitised provider info pointing at AnnexKit
itself as the "provider" — clearly a demo, not a real third party.

Usage
-----

  # Inside the running backend container:
  docker compose cp scripts/seed_demo.py backend:/tmp/seed_demo.py
  docker compose exec backend uv run python /tmp/seed_demo.py

To use a different slug:

  docker compose exec backend uv run python /tmp/seed_demo.py my-slug

To re-run idempotently (the tenant already exists):

  docker compose exec backend uv run python /tmp/seed_demo.py acme-saas

  → prints "tenant exists, api_key=…" if a key already exists, or mints
    a new one if not.

Idempotence notes
-----------------

  * Tenants are looked up by slug; rerunning with the same slug reuses
    the existing tenant.
  * AI systems are upserted via the same service the API uses
    (`ai_system_service.upsert`), so the deterministic risk classifier
    runs and the audit log records create-or-update events.
  * API keys are NOT regenerated if one already exists — a fresh key is
    only minted the first run, and the printout warns when reusing.
"""

from __future__ import annotations

import asyncio
import sys
from datetime import UTC, datetime

from sqlalchemy import select

from app.database import AsyncSessionLocal
from app.models.tenant import ApiKey, Tenant
from app.schemas.ai_system import AISystemDeclaration, ProviderInfo
from app.services import ai_system_service, api_key as api_key_service


DEMO_SYSTEMS: list[AISystemDeclaration] = [
    AISystemDeclaration(
        system_id="customer-support-bot",
        purpose=(
            "LLM-powered chatbot answering shipping, returns, and "
            "account questions over a 47-article FAQ knowledge base."
        ),
        annex_iii_categories=[],
        prohibited_practices=[],
        transparency_triggers=["chat_interaction"],
        is_gpai=False,
        provider_info=ProviderInfo(
            legal_name="Acme SaaS S.r.l. (demo)",
            address="Via Esempio 1, 37100 Verona, Italy",
            country="IT",
            system_version="v1.4.0",
            software_environment=(
                "Python 3.13, FastAPI, OpenAI gpt-4o-mini, Pinecone "
                "vector store, Postgres 16."
            ),
            hardware_environment="AWS Frankfurt, t3.medium app + RDS db.t3.small.",
            notes=(
                "This is an AnnexKit demo tenant. Fictitious data — not a "
                "real Acme SaaS customer. Generated by scripts/seed_demo.py."
            ),
        ),
    ),
    AISystemDeclaration(
        system_id="cv-screener",
        purpose=(
            "Pre-ranks incoming CVs against role profiles using "
            "sentence-transformers + a fine-tuned ranking head. Surfaces "
            "the top-20 candidates per role for a recruiter to review."
        ),
        annex_iii_categories=["employment_workers_management"],
        prohibited_practices=[],
        transparency_triggers=[],
        is_gpai=False,
        provider_info=ProviderInfo(
            legal_name="Acme SaaS S.r.l. (demo)",
            address="Via Esempio 1, 37100 Verona, Italy",
            country="IT",
            system_version="v0.9.2",
            software_environment=(
                "Python 3.13, sentence-transformers 3.x on-prem GPU, "
                "FastAPI inference server, Postgres 16."
            ),
            hardware_environment=(
                "Hetzner Falkenstein, GEX44 (NVIDIA RTX A4000), Ubuntu 24.04."
            ),
            validation_methods=(
                "Precision@20 = 0.78 measured against 1200 historical "
                "hire decisions across 6 role families. Adverse-impact "
                "ratio (selection rate of protected groups vs majority) "
                ">= 0.85 across age, gender, nationality. Quarterly "
                "re-validation on the most recent 3 months of decisions."
            ),
            notes="Demo tenant. Fictitious — generated by scripts/seed_demo.py.",
        ),
    ),
    AISystemDeclaration(
        system_id="loan-prescreen",
        purpose=(
            "First-pass eligibility screening for SME loan applications "
            "in the €10K-€100K range. Outputs an indicative tier; final "
            "decision always rests with a human credit officer."
        ),
        annex_iii_categories=["essential_services"],
        prohibited_practices=[],
        transparency_triggers=["chat_interaction"],
        is_gpai=False,
        provider_info=ProviderInfo(
            legal_name="Acme SaaS S.r.l. (demo)",
            address="Via Esempio 1, 37100 Verona, Italy",
            country="IT",
            authorised_representative=(
                "Acme SaaS S.r.l., Via Esempio 1, 37100 Verona, Italy."
            ),
            system_version="v2.4.1",
            software_environment=(
                "Python 3.13, FastAPI 0.136, Postgres 16 + pgvector, "
                "Mistral La Plateforme (Frankfurt) for advisor calls, "
                "internal policy KB indexed via dense retrieval."
            ),
            hardware_environment=(
                "AWS Frankfurt eu-central-1, c7i.large fronted by ALB."
            ),
            validation_methods=(
                "Back-tested against 5 years (~9000 decisions) of human "
                "credit-officer outcomes — concordance 84%. Disparate-"
                "impact testing on protected attributes (gender, age, "
                "geography). Adversarial robustness reviewed per "
                "OWASP LLM Top 10 (LLM01-LLM10) on every quarterly "
                "release. Decisions retained 10 years per Italian "
                "banking-supervision rules."
            ),
            notes=(
                "Demo tenant. Fictitious — not a real bank. Generated by "
                "scripts/seed_demo.py for the public trust page on annexkit.dev."
            ),
        ),
    ),
]


async def main() -> int:
    slug = sys.argv[1] if len(sys.argv) > 1 else "acme-saas"
    name = "Acme SaaS S.r.l. (demo)"

    async with AsyncSessionLocal() as session:
        # 1. tenant — create if missing, reuse if present.
        existing = await session.scalar(
            select(Tenant).where(Tenant.slug == slug)
        )
        if existing is None:
            tenant = Tenant(name=name, slug=slug)
            session.add(tenant)
            await session.flush()
            new_tenant = True
        else:
            tenant = existing
            new_tenant = False

        # 2. API key — only mint a fresh one if there is none yet.
        existing_key = await session.scalar(
            select(ApiKey).where(ApiKey.tenant_id == tenant.id)
        )
        if existing_key is None:
            generated = api_key_service.generate()
            session.add(
                ApiKey(
                    tenant_id=tenant.id,
                    name="seed-demo",
                    key_prefix=generated.prefix,
                    key_hash=generated.key_hash,
                )
            )
            api_key_plaintext = generated.plaintext
        else:
            api_key_plaintext = None  # cannot recover — was hashed.

        # 3. AI systems — upsert via the service so the deterministic
        #    classifier runs and the audit log records the event.
        for declaration in DEMO_SYSTEMS:
            await ai_system_service.upsert(
                session,
                tenant_id=tenant.id,
                payload=declaration,
            )

        await session.commit()

    # ---- Output -----------------------------------------------------
    print()
    print(f"slug={slug}")
    print(f"tenant_id={tenant.id}")
    print(f"tenant_status={'created' if new_tenant else 'reused'}")
    if api_key_plaintext:
        print(f"api_key={api_key_plaintext}")
        print()
        print("Copy api_key now — it is hashed in the DB and unrecoverable.")
    else:
        print("api_key=<existing — not shown; mint a new one via the API>")
    print()
    print("Demo trust page is now live:")
    print(f"  https://annexkit.dev/trust/{slug}")
    print(f"  https://annexkit.dev/trust/{slug}/systems/customer-support-bot")
    print(f"  https://annexkit.dev/trust/{slug}/systems/cv-screener")
    print(f"  https://annexkit.dev/trust/{slug}/systems/loan-prescreen")
    print()
    print(f"Seeded at {datetime.now(UTC).isoformat()}.")
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
